// 프로토콜 타입 정의
// 
#ifndef _PROTOCOLHEADER_H__
#define _PROTOCOLHEADER_H__

#define ARPPACKETSIZE			60
#define MACADDRESSLENGTH		6
#define IPV4ADDRESSLENGTH		4
#define ETHERNETHEADERLENGTH	14
#define MACADDRESSLENGTH		

#endif	// _PROTOCOLHEADER_H__ //